TableGroup users [note: 'User details'] {
  users.users
  users.sexes
}

TableGroup teams [color: #fcecec] {
  teams
  teams_users

  Note: 'The team tables'
}

Note my_note {
   'A note!'
}

table users.users [headercolor: #D3D3D3, url:'https://flexivis.infrastruktur.link/#url=text:inline:users.users+table+link'] {
  // Simple comment
  Id int [primary key, increment, not null]
  Name varchar(max) [not null]
  Sex int [ref: > users.sexes.Id]

  Note: 'a test note'
}

table users.sexes [headercolor: #200000, url:'https://flexivis.infrastruktur.link/#url=text:inline:users.sexes+table+link'] {
  /*
  Multiline comment
  */
  Note {
   'Male or female'
  }
  Id int [primary key, not null]
  Name varchar(10)
}

table teams [note: 'Another note'] {
  Id int [primary key]
  Name varchar(20)
}

table teams_users [url:'https://flexivis.infrastruktur.link/#url=text:inline:teams_users+join+table+link'] {
  Id int [primary key]
  TeamId int [ref: > teams.Id]
  UserId int [ref: > users.users.Id]
}
