TableGroup users {
  users.users
  users.sexes
}

table users.users [headercolor: #D3D3D3] {
  // Simple comment
  Id int [primary key, increment, not null]
  Name varchar(max) [not null]
  Sex int [ref: > users.sexes.Id]
}

table users.sexes [headercolor: #200000] {
  /*
  Multiline comment
  */
  Note: 'Male or female'
  Id int [primary key, not null]
  Name varchar(10)
}

table teams {
  Id int [primary key]
  Name varchar(20)
}

table teams_users {
  Id int [primary key]
  TeamId int [ref: > teams.Id]
  UserId int [ref: > users.users.Id]
}
