Table "[graph].[ProcedureInstance]"{
  "Procedure_fullname" nvarchar(261) [not null, Note: '''
  (concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
  ''']
  "Procedure_RepoObject_guid" uniqueidentifier [not null]
}
Table "[graph].[ProcedureInstance_S]"{
  "Procedure_RepoObject_guid" uniqueidentifier [not null, pk]
  "Instance" varchar(500) [not null, pk]
  "Procedure_fullname" nvarchar(261) [not null, Note: '''
  (concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
  ''']
}

Ref ref_name: "[graph].[ProcedureInstance]".(Procedure_fullname) > "[graph].[ProcedureInstance_S]".(Instance)[delete: Cascade, update: Cascade]
